language: r
sudo: false
cache: packages
warnings_are_errors: false
after_success:
  - Rscript -e 'covr::coveralls()'
notifications:
  email:
    recipients:
    - graeme.blair@ucla.edu
    - alex.coppock@yale.edu
    on_success: change
    on_failure: change
