language: r
sudo: false
cache: packages
warnings_are_errors: false
matrix:
  include:
  - os: linux
    r: release

  - os: linux
    r: oldrel
    after_success:
    - echo skipping source packaging on linux/oldrel

  - os: linux
    r: devel
    after_success:
    - echo skipping source packaging on linux/devel

  - os: osx
    r: release
    if: branch = master

  - os: osx
    r: oldrel
    if: branch = master

env:
  global:
  - OS=$(uname -s)
  - secure: OVXvZ2HzjL+pnzk9FOtTSk/F5LPONnNcFSJDIuAL/wAMPaqIwkqpSzd5v+mkgyxBBfW0Tm0y1Z+H/mI9YEeeG2QEJVOYiPjNh5Viu1QYYQvoAbyJ5Jtz9Z3PGGlA3Mj2+4QLoegEIKhdR0lDH7BsrdwnAboBM+aTbXsQdj4JkaeKnJBpItJECa3D6rTttzwNpMOs8N/lPMLJ1Ozjrj+hXm2IDRmhku+oH8tymdXnxz4z7CxImuOl4Z8CnWY+/8Of94/W5WL0JVyO5p7p9vKSPgWlBSNTwq6IfwhX30ziQACE08meAzSJ62JDPaTvbwVBMB3Bf0PCM+H8qnGE7mh8vqA2hc83wBHli8rGvsckNwS1qx/nfle/brCflENSZGuJg3SQQy4z9pWbPB3w9hiMGCTmY1945UVKz0jNc9p0oAFsgOfWS0cq9j/N/HHZ/D13fUgx6vzZiuKHv81oLEGGjGzpHJUmbUh1iLvtq9oyCKjkhXS74vyftkszPPgWcA9fmwuTCJgtREts3D8kRbbBLlDO5QpwRoaEgm1pPLcDiAuF6xH2Bu4E2XMvdfK6qK7Pl0+hNcg4cqVHoC9VXzSDC0XFr7FowqtcelJl5hCXObsbl6vhXh2Y4zO+wVrwOsJDYnxUAVUaM8Iyv3ci6Ww20haSWhGiVlLUaaSPuAtCUnU=
  - secure: Jz8S8RTYI1ol31b83k/zX1U7jSWXQ/dpK0KoDZOl3YumriHKYTiDxVlsEDVbRE/nHgbcchP30OJJOnfn5r9PgEfe9sw+1KopeTw/fKbtljXxZEdTrTE2LGjdhB5yD0CJ9dUF9vjG74BVIzn5YMQLJnVIOXjpnf7Br1JP5Hx7E2EMdqiOB4/DIo6+uRcLyDN5IGSf8ikm1yzdNPj99Tjf6vz0ntg4hgtCsFiwGPpomKoNArvtOH+v9z1aYhnuS2M4ZNr5yxZQIdEMwUzS2JF/XsQ8YMssPIrkcu3555SCA4vliPELnt0mdBB3Wn3n6XngBoDjGmAMw48YI849d3B8mVqjudvkMIJguIFpUyOESXkS+qxQUTMfn47NlP8g3PQE86vawfRX5Y4j2/jeirSIPLBdbHLVsEK5VBouRhzBg5MEnRTCdwcd/r9I6x/s7wH5r+jydZDPkdVedB4k1XrpxJZYKAWVE/ntV4ppJEO3b9ZQbngCAivJyI+5w8bcCHOfS7sb1+rdlEtzxShi21FkCiJCMVsv2+NZPJ0M0Zqe/X+z76TsbQYJNKhwhDaHNhN51fHM5gr4BxmO0mrcjxe4DgQYpwwvZJPMVLmS/9noe9QuIYLZ4vwFk58CA9IUviatgqhP/GNnKsW5z3BpkCwxGdhN1XOo1o3c0bAIRTo25Mo=
  - secure: QTan6097dNEpykGMniNg7UnbVCRb8qzyvo81Yp6KVOGqDSjOnRMLvSWRRybR7xubusB27OK9RZruno7RkkH3iRNgaYkYd48xAHW5cqTKrybMsOTim+Aij1e7gl7kNULQGpJJl0862C1/XMKmAVVwHktkKnlZmH/wGAuWs8quSqcXXpJ6ND6bJzfIQJYH6+b6PLsUPhzyIut3iUwfTE4nCpNikpwxP1TJGqKP42BpwCBEaSnlOumoIl5otsefSMH2+SzB2uNUtVfc8vOojhRR+OYJe4A9YearOrjcXa+N1qAz4O39023/lV20TU3thfStCeazs7a5X9yhd9vC6EGn5OovePO3HMlDHmV4kA7dQ+XGU7Lef0yA80F6bo9OVjsJqjc+gL28mDuaJpKMqomvaffoizuSiq0L82KvbRFxv8v+ZBabPbfg8Sgck9t3X1hlGtuXGMRhGSlq5P5JcWU0S2jd4VnFb/rbA+hXILPxEh4/4W3i53tgPFkspEIpI81LvfS/unxRUj0uFBP+a3HIb5WF/iaU+2oba+pH55p30qoz17wd1kVEQaIi1BOIP9eXPMwrypYqbSXQa7eXVQngY81ahwS2btUwwLkJ+jLKd+TukhOSQqoh2cFEvNbr39c/m1+ZrS7qsOvw4i2NOWz2XJCeRCmH3kRJP/7qeX8UyjM=
  - secure: ZJTeLgP/70/95TXGkStTWca/aQ9Xin+vaxg9OBmWwpBz5XF6YzphnlbLrN7mPoVjsMyz5IBWyfUAGEusPK+nwuEbbtYD3DCEqcE/GERvJTdJhIoRyvY4/E5WtL6HIJofft9dkN9WYCEbtbzRW47co9wBHmJwQbYLNmDSll66LIvo0OLvPkXnJNPWH5YH1lJslId7lE5szggpf6IvhqRWFW3pB5O3FHO6dgUwHxC9wqebcN784x29u5813jE9pItGjD/hdWbUeyabLqXzCz65Im73zvvqAIHCsLnrXgkcrKwknk3+iN4UFsDirU2Fv2RYCLDTKIq9Y7CSg0VukEeWUkrP8nnLj7MaC5d5L7UvfGP+U5u4xqIgoQpAlPNTidn3/til9+EDMlKQQ6Pi0r5F+5oHifLwz0am9HJtlNZvGH0CnuEtmlMd4hq32tvhHUiWR/790xNeaSNwQ48lSXPByunbRaCLZlig146jKZRbFNtueG+4S6WJJOZTupl7+TR9tT8zymFMK8G5NrYtZD/EMSLsMbjc0BgrtErJ5t0ZRKJeERC5DmrY6T5x0Thz7lCGjqA2l6CjaWHa8xixUf45DL8iAyBoZtQvUU/fxID5UpbWEPTMrIAK3Be1YGi0stbO4fqb5NIl2R5ScrtKL3nEDq2S6Ze0UZ/gYDsYWkHZe/A=

r_github_packages:
- DeclareDesign/DDtools
- ropensci/git2r

after_success:
- Rscript -e DDtools::after_build
